### PR TITLE
doc.go: Fix gramma 'deserialzied' -> 'deserialized'

### PR DESCRIPTION
**Pull request by DenLilleMand**

### CODE REVIEW

**Comment by DenLilleMand** [comment]
I signed it

**Comment by StephanEggermont** [comment]
Is this project unmaintained?

**Comment by DenLilleMand** [comment]
> Is this project unmaintained?

I can't talk for anyone on this project, but from the outside, it looks like yes. The last commit was 4 months ago, and it was to a travis file.

**Comment by StephanEggermont** [comment]
And this is a two-year old trivial typo, that only needs merging. Hmm.

**Pull request merged**
