### PR TITLE
Add support for 'meta'

### PR DESCRIPTION
**Pull request by sbelkin88**

### CODE REVIEW

**Comment by genexp** [comment]
Very nice!  Question on this.. I wonder if we should support creating objects with meta too?  We support creating objects with relationships.

**Comment by sbelkin88** [comment]
@genexp I believe this PR accomplishes that, but can you please clarify if you're looking for something different?  This PR allows meta to be added at the resource object-level and relationship level.  Then, in the same vein as the recent PR for Links, we can add meta at the top level by doing something like:

```
payload, _ := jsonapi.MarshalMany(blogPosts)

payload.Meta = &jsonapi.Meta{
	"details": "extra information here",
}

json.NewEncoder(w).Encode(payload)
```

**Comment by genexp** [comment]
Hey Samantha - I guess I was asking about UnmarshalMany, and receiving metadata.  After re-reading the spec, I'm actually not sure if this is possible or not.  I can see it being useful (we let games submit data to us, and having the ability to add metadata about how it was received would be handy), but I don't think we should deviate in any way from spec.

**Comment by sbelkin88** [comment]
Hi @aren55555 - I saw the @googlebot's message above, but I believe I am the author for all the commits in this branch.  Can you please help advise if there is any action needed, or where the other author is so I can contact them if necessary?  Also, are you able to advise on what the `feature/meta` branch is, and whether that will be merged into master?

**Comment by aren55555** [comment]
@sbelkin88 the @googlebot is because I resolved the conflict. The mixed branch authors cause that  message; in this case it can be ignored.

As for the `feature/meta` there are a couple changes that need to be made including:

- Making the Links objects implement the interface
- Adding examples to the example app and fixtures

I've already started on both of those and will mention this PR when I open a PR to merge `feature/meta` to `master`. I was not able to commit directly to your branch (when you submit a PR there is an option to allow us to contribute back to your source branch that was not checked) so I had to go with this option.

**Comment by aren55555** [comment]
See https://github.com/google/jsonapi/pull/81 for the subsequent changes I made.

**Pull request merged**
