### PR TITLE
Unmarshal struct attributes

### PR DESCRIPTION
**Pull request by henrmota**
Add the ability to marhsal and unmarhsal custom struct attributes as well custom struct slices, either pointers or not

### CODE REVIEW

**Comment by mkarlesky** [comment]
@shwoodard What needs to happen for this PR to be merged? It appears to fix issues #156 and #164. I confess that there are subtle issues involved that I don't fully grasp. But, I believe I want to use the fixes of this PR instead of relying on a commit from March before the unmarshaling issues were introduced.

**Comment by Marahin** [comment]
Can we _please_ get this merged? Its something that should be in the library at this point.

**Comment by fabrepe** [comment]
Any news on this PR ? Why cannot it be merged ?
While this is not merged we need to use @henrmota repository as go module.

**Comment by mellena1** [comment]
I would also like to see this merged if possible. I am in agreement with @mkarlesky in the sense that I don't grasp some of the subtle issues, but I think this is an important feature to have.

**Comment by codyaray** [comment]
Please provide a status update. :(

**Pull request closed without merging**
