### PR TITLE
Fix omitempty for attributes

### LINKED ISSUE #103: runtime error: comparing uncomparable type Garden.Gardens
This struct point to another struct in another package

```go
type User struct {
	ID        int64  `jsonapi:"primary,user"`
	Name      string `jsonapi:"attr,name"`
	Gardens   Garden.Gardens `jsonapi:"attr,garden,omitempty"`
}
```
The `Garden.Gardens` type is:

```go
type Gardens []*Garden
```
When the code reach

```go
	return jsonapi.MarshalPayload(c.Response(), &u)
```
I get
>echo: http2: panic serving 127.0.0.1:40812: runtime error: comparing uncomparable type Garden.Gardens
>goroutine 21 [running]:
>net/http.(*http2serverConn).runHandler.func1(0xc420216008, 0xc42025bfaf, 0xc42020e000)
>        /opt/go/src/net/http/h2_bundle.go:4604 +0x190
>panic(0x78f880, 0xc4201c9f10)
>        /opt/go/src/runtime/panic.go:489 +0x2cf
>github.com/google/jsonapi.visitModelNode(0x7cd5a0, 0xc4202620a0, 0xc42025b958, 0x1, 0xc4201cb770, 0xc4202620a0, 0x16)
>        /path/src/github.com/google/jsonapi/response.go:344 +0xaab
>github.com/google/jsonapi.marshalOne(0x7cd5a0, 0xc4202620a0, 0x16, 0x7e21a0, 0xc4202620a0)
>        /path/src/github.com/google/jsonapi/response.go:143 +0x7d
>github.com/google/jsonapi.Marshal(0x7cd5a0, 0xc4202620a0, 0xc42025ba28, 0x42b82b, 0x7fc100, 0x1)
>        /path/src/github.com/google/jsonapi/response.go:111 +0x34c
>github.com/google/jsonapi.MarshalPayload(0x98e4a0, 0xc42023a050, 0x7cd5a0, 0xc4202620a0, 0xc4200b4c60, 0xa5)
>        /path/src/github.com/google/jsonapi/response.go:66 +0x4d

If i replace the `attr` with `relation` it works as expected:

```go
	Gardens   Garden.Gardens `jsonapi:"relation,garden,omitempty"`
```

Is it a bug or maybe misuse on my side?

### PR DESCRIPTION
**Pull request by hypnoglow**
Fix panic on omitempty field for attribute that is not of
a primitive type.

Fixes #103

### CODE REVIEW

**Comment by shwoodard** [comment]
This lgtm, @aren55555, what do you think, ok to merge?

**Comment by shwoodard** [comment]
@hypnoglow Please add a test for non slice type

**Comment by aren55555** [comment]
@shwoodard looks good to me; the negative test case would be nice!

**Comment by hypnoglow** [comment]
@shwoodard @aren55555  I've added fields of types struct and map; test for the map is the negative one if you meant the field should not be omitted if it is not empty.

**Pull request merged**
